ccflags-y += -Idrivers/media/platform/msm/camera_v2_sailfishos
ccflags-y += -Idrivers/media/platform/msm/camera_v2_sailfishos/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_sailfishos/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
