ccflags-y += -Idrivers/media/platform/msm/camera_v2_sailfishos
ccflags-y += -Idrivers/media/platform/msm/camera_v2_sailfishos/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_sailfishos/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
